version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "helloStack"
s3_bucket = "robot-reach-test-deploy"
s3_prefix = "helloStack"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
