AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Hello World Example

  Sample SAM Template for Hello World Example
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code/
      Handler: helloworld.helloWorldHandler
      Runtime: nodejs12.x
      Layers:
        - !Ref TempConversionDepLayer
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
  EmblematicDB: 
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceIdentifier: robot-reach-instance-cf
      DBSnapshotIdentifier: arn:aws:rds:eu-north-1:013058818715:snapshot:empty-robot-reach-final-snapshot
      DeletionProtection: True
      Engine: "postgres"
  
  TempConversionDepLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: lambda-functions-dependencies
            ContentUri: dependencies/
            CompatibleRuntimes:
              - nodejs8.10
              - nodejs12.x
            LicenseInfo: 'MIT'
            RetentionPolicy: Retain

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  EmblematicDB:
    Description: InstanceId of the newly created RDS Instance
    Value: !Ref EmblematicDB 
